services:
  postgres:
    image: postgres:17.4
    environment:
      POSTGRES_USER: jsonviewer
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jsonviewer
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5555:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jsonviewer -d jsonviewer"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: json-viewer-backend
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./backend/.env
    environment:
      PORT: 3001
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: json-viewer-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    # Use nodemon to watch for changes and restart the server
    command: sh -c "bun install && bun run dev"
    environment:
      - NODE_ENV=development

volumes:
  postgres_data:
